wandb_version: 1

learning_rate:
  desc: null
  value: 0
architecture:
  desc: null
  value: log
dataset:
  desc: null
  value: Lihu-domi_lowres
epochs:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717153888
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
